version: '2'

services:
  axonbank1:
    image: axonframework/axonbank
    depends_on:
      - db
    ports:
      - "8080:8080"
  axonbank2:
    image: axonframework/axonbank
    depends_on:
      - db
    ports:
      - "8081:8080"
  db:
    image: mysql:5.7.15
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=axonbank
    ports:
            - "3306:3306"
  rabbitmq:
    build: docker/rabbitmq/
    ports:
        - "15672:15672"
        - "5672:5672"
        - "61613:61613"